### ISSUE TITLE
About Wavelet Decomposition in Models

### ISSUE THREAD

**Issue by moelmadoka** [mxbastidasr/DAWN_WACV2020#6]
Sorry to disturb you.
Isn't the method in the article combined with haar wavelet decomposition? We found  that haar_wavelet is Fasle by default in the code, and the wavelet decomposition part is imitated by convolution operation, but it is not the haar wavelet decomposition.
Looking forward to your reply.

**Comment by beltegeuse** [comment]
Hi Moelmadoka,

The Haar wavelet decomposition is one possible architecture of our network (when the decomposition is not learned through the lifting scheme). It is why by default, this option is set to False. 

Note that this repository contains the non-official implementation of "Wavelet Convolutional Neural Networks for Texture Classification," as we compare to this technique inside the paper.

Tell me if I have answered your question.

**Comment by moelmadoka** [comment]
Thank you for your reply.
We mistakenly believe that this paper embeds a classical wavelet decomposition network into a CNN, and this may use an alternating optimization strategy to train the model.
