### ISSUE TITLE
invertibility

### ISSUE THREAD

**Issue by eecoder-dyf** [mxbastidasr/DAWN_WACV2020#7]
Hello,
As we known that the wavelet transform is invertible, so I'm interested that if the wavelet lifting is invertible?

**Comment by mxbastidasr** [comment]
It is actually. We performed some tests. And you can obtain the weights in a forward analysis, then freeze those weights and recover the image, similar as with the wavelet transform

**Comment by beltegeuse** [comment]
Note our network design shares similarities with NICE network architecture: https://arxiv.org/pdf/1410.8516.pdf, which is invertible and can provide you with a PDF.
